import math
"""Globale Game Variablen"""
fps = 60
step = 1 / fps
width = 1024
height = 768
segments = []
screen = None
background = None
sprites = None
resolution = None
roadWidth = 2000
segmentLength = 200
rumbleLength = 3
trackLength = 0
lanes = 3
fieldOfView = 100
cameraHeight = 1000
cameraDepth = 1 / math.tan((fieldOfView / 2) * math.pi / 180)
drawDistance = 500
segment_count = 600
playerX = 0
playerZ = (cameraHeight * cameraDepth)
fogDensity = 15
position = 0
speed = 0
maxSpeed = 24000
accel = maxSpeed / 5
breaking = -maxSpeed
decel = -maxSpeed / 5
offRoadDecel = -maxSpeed / 2
offRoadLimit = maxSpeed / 4
clock = None
centrifugal = 0.37
keyLeft = False
keyRight = False
keyFaster = False
keySlower = False
total_cars = 30
dt = 1 / 30
cars = []
player = None
background_sprite_group = None
player_sprite_group = None
